### ISSUE TITLE
hotkey to like/unlike songs

### ISSUE THREAD

**Issue by jacksonday** [HermesApp/Hermes#159]
would be great to see/hear a song come on and hit a hotkey to influence the current station.

**Comment by jacksonday** [comment]
I've been using bettertouchtool to send hotkey strokes to hermes from outside the app.

However  Is there a way (via applescripts or otherwise) to use a hotkey to open the lyrics for the currently playing song?
I'm aware of the button under song history

**Comment by nriley** [comment]
You could replicate what Hermes does — decode JSON from the Wikia lyrics API.  There's not an easy way to expose Hermes’ exact functionality via AppleScript (it's not impossible, but would require quite a bit of work because you'd have to avoid blocking the app while it makes a network request).  It's probably easiest to reproduce the behavior in your own scripting code.

Here’s the relevant Hermes code:

https://github.com/HermesApp/Hermes/blob/f03f464648259072fc94d5f4224a236b7c6ac366/Sources/Controllers/HistoryController.m#L190
