### ISSUE TITLE
Logging in does not always present station drawer for station selection

### ISSUE THREAD

**Issue by winny-** [HermesApp/Hermes#170]
Logged out (Pandora -> Log Out) then logged in. Notice the history drawer and the window title.

![image](https://cloud.githubusercontent.com/assets/3893828/2689030/0a43da0a-c2df-11e3-8fba-04c5f9e77c23.png)

**Comment by nriley** [comment]
This is better now — we don't try to hide the toolbar any more (7f18720b3142c76f76002a4d9ec61133716e3f73) since it validates (c121cfae23ed6da7f9c59132d00e16b0b827f48b), we don't allow the drawer to be shown when not logged in (d4c17de604dc367b389ba11191753727e82b8c6f), and we now show the stations drawer when asking the user to choose a station (b86cc220c9f059f659c0475e7863768b65c01e4f).

<img width="529" alt="better" src="https://cloud.githubusercontent.com/assets/68303/16176850/c87d54e6-35e8-11e6-9513-e87389d27025.png">
