### ISSUE TITLE
last.fm error: Unexpected end of input

### ISSUE THREAD

**Issue by skywinder** [HermesApp/Hermes#216]
This error appear with all new track that I play + every 1-2 minute after.
![screen shot 2015-02-06 at 18 31 26](https://cloud.githubusercontent.com/assets/3356474/6083042/9640af48-ae2e-11e4-9a38-a0d4889c0935.png)

**Comment by DrPat** [comment]
This same error has started happening today with Hermes on my macbook pro. Also, it has been acting a little buggy since around the time of the update. The desktop interface will not respond to a song that is playing that is not shown at all just in the background Hermes controls on the desktop interface do not respond but when double clicking the tray icon it will change songs or turn off songs. Been have a lot of audio streaming failures too. Album art missing on songs happens too - Pat

**Comment by nriley** [comment]
I've done a lot of work on the Last.fm integration in 1.2.7 — if this is still a problem in that version please let us know.
