### ISSUE TITLE
Feature Request: Ads blocker

### ISSUE THREAD

**Issue by DrPat** [HermesApp/Hermes#218]
Well Ads have arrived they come looking like songs but advertise various products while showing a picture of my favorite song. If they were not so frequent.

**Comment by DrPat** [comment]
There is so many ads every station I had to turn it off sorry but this is a bit much.

**Comment by winny-** [comment]
Sorry, this is an issue with Pandora. We are working on indicating that a song is actually an ad in the UI. To avoid the songs that are actually ads, I suggest becoming a Pandora One member.

More information on the issue:
* [pithos/pithos: issue 73, Ads cause song to be skipped.](https://github.com/pithos/pithos/issues/73)
* [PromyLOPh/pianorbar: issue 415, Ads randomly playing](https://github.com/PromyLOPh/pianobar/issues/415)
* Detect Inline Ads #189

**Comment by DrPat** [comment]
(rant Warning) Well yes I could.. i am a free- hunter though... this would only send me on a hunt..  I make no bones about it... its is fun to find free projects we do get taken advantage of so much these days ... (begin rant) the ad attacks are everywhere and it feels like the internet will start showing ads if we don't cough up another few fees. As long as people offer to fight the fight I am a fighter.... (end rant)

**Comment by winny-** [comment]
You must keep in mind that no website is free.

There are many different revenue models. GitHub relies on Enterprise customers and private repositories. Pandora relies on subscribers and advertisements, as does Spotify and iTunes Radio.

If Pandora wants to recoup some of their lost revenue from clients that don't play advertisements, instead of blocking these clients—or worse, blocking the users that use such clients—I say it's a great thing.

**Comment by DrPat** [comment]
You are right.. it is kindness  to lower profits in order to benefit others. It is also a well used business model nowadays. Ignore my complaints I have a thing with not having control that is all. I like the app and pandora and do not mind an ad or two..

**Comment by winny-** [comment]
Thank you for understanding. I'm going to lock this issue for the time being.
