### ISSUE TITLE
Issue running on OSX 10.11

### ISSUE THREAD

**Issue by ralphmason** [HermesApp/Hermes#234]
Button graphic are not display correctly in the OSX 10.11 beta

![image](https://cloud.githubusercontent.com/assets/7388236/8072212/c81640ec-0ec7-11e5-8b1b-03a00491838c.png)

**Comment by winny-** [comment]
Are there any warnings in the logs? `/Applications/Utilities/Console.app` → Search for Hermes

**Comment by gothickitty93** [comment]
6/12/15 6:05:20.764 PM Hermes[74154]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.0 instead of 10.11.0. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
6/12/15 6:05:20.765 PM Hermes[74154]: 0   CarbonCore                          0x00007fff9035e6f3 ___Gestalt_SystemVersion_block_invoke + 113
6/12/15 6:05:20.765 PM Hermes[74154]: 1   libdispatch.dylib                   0x00007fff97163383 _dispatch_client_callout + 8
6/12/15 6:05:20.765 PM Hermes[74154]: 2   libdispatch.dylib                   0x00007fff9716327b dispatch_once_f + 67
6/12/15 6:05:20.765 PM Hermes[74154]: 3   CarbonCore                          0x00007fff902e9a21 _Gestalt_SystemVersion + 987
6/12/15 6:05:20.765 PM Hermes[74154]: 4   CarbonCore                          0x00007fff902e8cb5 Gestalt + 139
6/12/15 6:05:20.765 PM Hermes[74154]: 5   Growl                               0x0000000102ab3f40 GrowlGetSystemVersion + 36
6/12/15 6:05:20.765 PM Hermes[74154]: 6   Growl                               0x0000000102ab2811 +[GrowlGNTPPacket addSentAndReceivedHeadersFromDict:toArray:] + 799

**Comment by cpowell** [comment]
Confirmed - it's not just the El Capitan beta, it's the 10.11.0 GA release too. Slight difference in the missing elements, however - it seems limited to progress bar and volume slider here.

**Comment by esambo** [comment]
I am NOT having this issue on OS X El Capitain 10.11

**Comment by nriley** [comment]
Please note that Hermes is essentially an abandoned project — if anyone wants to work on fixing this, great, but neither Alex, Winston nor I are actively working on it nor do any of us have any plans to do so in the near future.  (For what it's worth, I do not see this on my 10.11 Mac.)

**Comment by sirg3** [comment]
I can reproduce this and, in the few minutes I had available, narrowed it down to the CIFilters being added to the NSSliders.

**Comment by nriley** [comment]
Looks like Apple (re)introduced some bugs in layer-backed/hosted views (can never remember which is which).  Sigh.  That makes a lot of sense.

**Comment by cpowell** [comment]
I wonder if (and how) it might be related to the nVidia drivers. I switched to the stock OS X driver (away from the nVidia web driver) and now I have my Hermes UI back.

**Comment by sirg3** [comment]
Sounds plausible. I'm also running the web drivers, though I can't easily switch back to the stock drivers to test the theory.

**Comment by JohnDDuncanIII** [comment]
I've been using Hermes on OS X 10.11 developer beta 1 through 10.11.2 Beta 3 and have not run into any of these issues, for what it's worth. 
![hermes](https://cloud.githubusercontent.com/assets/9257785/11166300/00b6c5d8-8afc-11e5-8905-ebb3e21a3958.png)

**Comment by nriley** [comment]
I haven't seen this in ages, so I think it's probably not a Hermes bug and fixed. Please feel free to comment if it's still happening for you.
