### ISSUE TITLE
Seeds list does not work

### ISSUE THREAD

**Issue by deltamikeecho** [HermesApp/Hermes#267]
Current Seeds list is empty, unable to even type in the search field to add new Song or Artist to seed list.  Affects 1.2.7 and 1.2.8b1.

**Comment by nriley** [comment]
Sorry, I can't reproduce this — it works for me in both versions on both 10.10 and 10.11 (modulo the bugs I fixed in 1.2.8).  What happens when you type in the search field?  Does this affect both the search field in the New Station sheet as well as the Edit Station window?

If it's still broken for you, try posting the debugging output from Hermes — launch Hermes while holding down the Option key, try to do a search, then attach the most recent log from ~/Library/Logs/Hermes.  Thanks!

**Comment by deltamikeecho** [comment]
I did a  little more investigation and found that the stations on which I can't edit the Seeds are stations that were created from a Pandora Genre Station.  On this particular station I tested with I had long ago (2012) selected the option to 'make it my own' and can fully manage Seeds and Tracks through the web interface but am unable to do so through Hermes.

I confirmed that on a statio I created from scratch I am able to manage the Seed list through Hermes.

I attached the log created from performing these steps: opened Hermes, went to the station, selected edit and tried to type in the search field of the Seed list, quit Hermes.
[HermesLog_2016-06-14_13:04:20_-0400.zip](https://github.com/HermesApp/Hermes/files/314501/HermesLog_2016-06-14_13.04.20_-0400.zip)

**Comment by nriley** [comment]
The support for genre stations was a bit of a mess and what you ran into was far from obvious — there were actually some tooltips that explained why the list wasn't editable, but I certainly didn't know about them!

In 1.2.8b2, I've just removed the Seeds tab entirely for stations where it doesn't apply.  I also cleaned up a bunch of other things related to genre stations and likes/dislikes.

https://github.com/HermesApp/Hermes/releases/tag/v1.2.8b2

Thanks for testing!

**Comment by nriley** [comment]
Well, that was the shortest-lived Hermes release ever.  It turns out the part of the Pandora API that claims these stations aren't editable is just returning incorrect information (more likely, a relic of a past time when they weren't — sounds like prior to 2012 from your description).

1.2.8b3 should let you edit your genre stations’s regardless of what Pandora says.

https://github.com/HermesApp/Hermes/releases/tag/v1.2.8b3

**Comment by deltamikeecho** [comment]
looks like that did the trick!  They used to call them, and maybe still do, "Shared" stations.  If you attempted to thumb up/down a song it would warn you that it was a shared station and ask if you wanted to make it your own, meaning make a copy of it so it could be edited.  

Speaking of Thumb up/down, found another issue with it, will open a new bug.
