### ISSUE TITLE
Bitrate Differences?

### ISSUE THREAD

**Issue by fridaynext** [HermesApp/Hermes#270]
I know this isn't directly related to Hermes, but I've been Googling everywhere and can't seem to find an answer. Is free Pandora 128kbps and Pandora One 192kbps? I'm trying to research if there's any good reason to pay for One.

**Comment by nriley** [comment]
Results from testing I did a couple months ago are in 59f095cee88292481f7716000b1dd28e7797e1b3.

In short, yes, you are correct; the best bit rate you are going to get without Pandora One is a 128 Kbps MP3.  I don’t expose the bit rates in the user interface anywhere because they are subject to change, though in reality they generally don’t.  If you turn on logging, they will print in the log. I do subscribe to Pandora One so I get the following:

```
Pandora.m:519 __35-[Pandora fetchPlaylistForStation:]_block_invoke High quality audio from audioUrlMap is 192 Kbps mp3
Pandora.m:525 __35-[Pandora fetchPlaylistForStation:]_block_invoke Medium quality audio from audioUrlMap is 64 Kbps aacplus
[...]
Station.m:157 -[Station songsLoaded:] Received hermes.fragment-fetched.3180035288299880094 from (null) with qualities: high high high high
[...]
HistoryController.m:26 -[HistoryController loadSavedSongs] loading saved songs
ASPlaylist.m:78 -[ASPlaylist bitrateReady:] <AudioStreamer: 0x7f83420c0e00> 44.1 KHz '.mp3' ~192 Kbps
```
