### ISSUE TITLE
Hermes crashes on launch

### ISSUE THREAD

**Issue by oey192** [HermesApp/Hermes#327]
1. Launch Hermes
2. The side tray opens (I normally have it opens)
3. The app freezes (spinning beachball of death)
4. After some time (sometimes a few seconds, sometimes 15+ seconds), the app crashes

Note: My computer is experiencing bluetooth issues which may be causing the problem (computer shows Bluetooth headphones/headset as connected but they will not play audio, audio selector doesn't recognize Bluetooth as valid playback device, headset itself doesn't recognize that it is connected to the computer, headset connects to phone, headset iPhone app times out when attempting to connect headset to computer (headset can connect to two Bluetooth devices at once)

Crash report:
[Hermes_2018-01-03-104142_186590d001d7.txt](https://github.com/HermesApp/Hermes/files/1601381/Hermes_2018-01-03-104142_186590d001d7.txt)

**Comment by oey192** [comment]
Note: restarting my computer fixed the bluetooth issue and Hermes now launches without crashing. Before restarting, this issue was 100% repro

**Comment by nriley** [comment]
Crash report looks similar to a couple others (e.g. #322) which indicate that AudioToolbox has some issues when audio doesn't deliver as expected, whether due to flaky Bluetooth, heavy system load or something else. I'm going to close this issue as your particular crash is resolved, but it seems to be not 100% Apple's problem.
