### ISSUE TITLE
Keeps playing music on its own in middle of night

### ISSUE THREAD

**Issue by ghost** [HermesApp/Hermes#355]
I slept somewhere else last night and came home this morning to a note that said something like "hey your music was on all night long - wtf" and my Hermes client was blasting music when I opened the door. This has happened twice in the past year.

I don't know if my mac is waking from sleep or what, but Hermes is somehow getting triggered to start playing on its own, which is a no go!

**Comment by perryclarke** [comment]
This probably happened because Hermes starts playing the last tuned station when it is opened and your Mac restarted after installing updates (or something similar) and reopened the previously open apps.  Ideally the Hermes would start playing when started interactively (by double-clicking the icon) but not when started autonomously by the operating system.  Unfortunately detecting the difference between these two cases is Hard™  but I'm looking into it since I've had similar experiences.  Perhaps it would be enough if it just remembered whether it was paused and not start playing in that case.

**Comment by ghost** [comment]
Crazy story. Turns out I had an RDP port open and a hacker was remoting in and kicking off these late night sessions. The auto-play helped me catch them in the act!!!
